/* eslint-disable no-restricted-globals */

// This service worker is using Workbox under the hood
// through the Create React App PWA template
import { clientsClaim } from 'workbox-core';
import { ExpirationPlugin } from 'workbox-expiration';
import { precacheAndRoute, createHandlerBoundToURL } from 'workbox-precaching';
import { registerRoute } from 'workbox-routing';
import { StaleWhileRevalidate, CacheFirst } from 'workbox-strategies';

// Claim clients immediately
clientsClaim();

// Precache all of the assets generated by your build process
const WB_MANIFEST = self.__WB_MANIFEST;
precacheAndRoute(WB_MANIFEST);

// Set up App Shell-style routing for SPA
const fileExtensionRegexp = new RegExp('/[^/?]+\\.[^/]+$');
registerRoute(
  // Return false to exempt requests from being handled by this route
  ({ request, url }) => {
    // If this is a navigation request, let workbox precaching handle it
    if (request.mode === 'navigate') {
      return true;
    }

    // Return false for URLs ending in file extensions like .jpg, .png, etc.
    if (url.pathname.match(fileExtensionRegexp)) {
      return false;
    }

    // Return true for same-origin URLs that don't end in file extensions
    return true;
  },
  createHandlerBoundToURL(process.env.PUBLIC_URL + '/index.html')
);

// Cache the Google Fonts stylesheets with a stale-while-revalidate strategy
registerRoute(
  ({ url }) => url.origin === 'https://fonts.googleapis.com',
  new StaleWhileRevalidate({
    cacheName: 'google-fonts-stylesheets',
  })
);

// Cache the underlying font files with a cache-first strategy for 1 year
registerRoute(
  ({ url }) => url.origin === 'https://fonts.gstatic.com',
  new CacheFirst({
    cacheName: 'google-fonts-webfonts',
    plugins: [
      new ExpirationPlugin({
        maxAgeSeconds: 60 * 60 * 24 * 365, // 1 year
        maxEntries: 30,
      }),
    ],
  })
);

// Cache images with a cache-first strategy
registerRoute(
  ({ request }) => request.destination === 'image',
  new CacheFirst({
    cacheName: 'images',
    plugins: [
      new ExpirationPlugin({
        maxEntries: 60,
        maxAgeSeconds: 30 * 24 * 60 * 60, // 30 Days
      }),
    ],
  })
);

// Background sync for failed API requests
self.addEventListener('sync', (event) => {
  if (event.tag === 'sync-violations') {
    event.waitUntil(syncViolations());
  }
});

// Function to sync stored violations when back online
async function syncViolations() {
  try {
    const db = await openDB();
    const tx = db.transaction('sync-store', 'readonly');
    const store = tx.objectStore('sync-store');
    const pendingItems = await store.getAll();
    
    if (pendingItems.length === 0) return;
    
    // Here you would send the data to your server API
    // For example:
    // const syncResults = await Promise.all(
    //   pendingItems.map(item => fetch('/api/violations', {
    //     method: 'POST',
    //     headers: { 'Content-Type': 'application/json' },
    //     body: JSON.stringify(item)
    //   }))
    // );
    
    // After successful sync, clear the sync store:
    const clearTx = db.transaction('sync-store', 'readwrite');
    const clearStore = clearTx.objectStore('sync-store');
    await clearStore.clear();
    
    // Notify clients that sync is complete
    const clients = await self.clients.matchAll();
    clients.forEach(client => {
      client.postMessage({
        type: 'SYNC_COMPLETE',
        payload: { count: pendingItems.length }
      });
    });
    
  } catch (error) {
    console.error('Sync failed:', error);
  }
}

// Function to open IndexedDB
async function openDB() {
  return new Promise((resolve, reject) => {
    const request = indexedDB.open('vehicle-violations-db', 1);
    
    request.onerror = () => reject(request.error);
    request.onsuccess = () => resolve(request.result);
    
    request.onupgradeneeded = (event) => {
      const db = event.target.result;
      if (!db.objectStoreNames.contains('violations')) {
        db.createObjectStore('violations', { keyPath: 'id' });
      }
      if (!db.objectStoreNames.contains('sync-store')) {
        db.createObjectStore('sync-store', { keyPath: 'id' });
      }
    };
  });
}

// Listen for messages from the client
self.addEventListener('message', (event) => {
  if (event.data && event.data.type === 'SKIP_WAITING') {
    self.skipWaiting();
  }
});